export const bangladeshiDistricts = [
  { id: 1, name: "Dhaka" },
  { id: 2, name: "Faridpur" },
  { id: 3, name: "Gazipur" },
  { id: 4, name: "Gopalganj" },
  { id: 5, name: "Kishoreganj" },
  { id: 6, name: "Madaripur" },
  { id: 7, name: "Manikganj" },
  { id: 8, name: "Munshiganj" },
  { id: 9, name: "Narayanganj" },
  { id: 10, name: "Narsingdi" },
  { id: 11, name: "Rajbari" },
  { id: 12, name: "Shariatpur" },
  { id: 13, name: "Tangail" },
  { id: 14, name: "Chattogram" },
  { id: 15, name: "Bandarban" },
  { id: 16, name: "Brahmanbaria" },
  { id: 17, name: "Chandpur" },
  { id: 18, name: "Cox's Bazar" },
  { id: 19, name: "Cumilla" },
  { id: 20, name: "Feni" },
  { id: 21, name: "Khagrachari" },
  { id: 22, name: "Lakshmipur" },
  { id: 23, name: "Noakhali" },
  { id: 24, name: "Rangamati" },
  { id: 25, name: "Barishal" },
  { id: 26, name: "Barguna" },
  { id: 27, name: "Bhola" },
  { id: 28, name: "Jhalokati" },
  { id: 29, name: "Patuakhali" },
  { id: 30, name: "Pirojpur" },
  { id: 31, name: "Khulna" },
  { id: 32, name: "Bagerhat" },
  { id: 33, name: "Chuadanga" },
  { id: 34, name: "Jashore" },
  { id: 35, name: "Jhenaidah" },
  { id: 36, name: "Kushtia" },
  { id: 37, name: "Magura" },
  { id: 38, name: "Meherpur" },
  { id: 39, name: "Narail" },
  { id: 40, name: "Satkhira" },
  { id: 41, name: "Mymensingh" },
  { id: 42, name: "Jamalpur" },
  { id: 43, name: "Netrokona" },
  { id: 44, name: "Sherpur" },
  { id: 45, name: "Rajshahi" },
  { id: 46, name: "Bogura" },
  { id: 47, name: "Joypurhat" },
  { id: 48, name: "Naogaon" },
  { id: 49, name: "Natore" },
  { id: 50, name: "Pabna" },
  { id: 51, name: "Sirajganj" },
  { id: 52, name: "Chapainawabganj" },
  { id: 53, name: "Rangpur" },
  { id: 54, name: "Dinajpur" },
  { id: 55, name: "Gaibandha" },
  { id: 56, name: "Kurigram" },
  { id: 57, name: "Lalmonirhat" },
  { id: 58, name: "Nilphamari" },
  { id: 59, name: "Panchagarh" },
  { id: 60, name: "Thakurgaon" },
  { id: 61, name: "Sylhet" },
  { id: 62, name: "Habiganj" },
  { id: 63, name: "Moulvibazar" },
  { id: 64, name: "Sunamganj" }
];


export const bdDivision = [
  { id: 'Dh', name: 'Dhaka' },
  { id: 'Ch', name: 'Chattogram' },
  { id: 'Ra', name: 'Rajshahi' },
  { id: 'Kh', name: 'Khulna' },
  { id: 'Ba', name: 'Barishal' },
  { id: 'Sy', name: 'Sylhet' },
  { id: 'Ra', name: 'Rangpur' },
  { id: 'My', name: 'Mymensingh' }
];