export const bangladeshiDistricts = [
  { id: 1, name: "Dhaka" },
  { id: 2, name: "Faridpur" },
  { id: 3, name: "Gazipur" },
  { id: 4, name: "Gopalganj" },
  { id: 5, name: "Kishoreganj" },
  { id: 6, name: "Madaripur" },
  { id: 7, name: "Manikganj" },
  { id: 8, name: "Munshiganj" },
  { id: 9, name: "Narayanganj" },
  { id: 10, name: "Narsingdi" },
  { id: 11, name: "Rajbari" },
  { id: 12, name: "Shariatpur" },
  { id: 13, name: "Tangail" },
  { id: 14, name: "Chattogram" },
  { id: 15, name: "Bandarban" },
  { id: 16, name: "Brahmanbaria" },
  { id: 17, name: "Chandpur" },
  { id: 18, name: "Cox's Bazar" },
  { id: 19, name: "Cumilla" },
  { id: 20, name: "Feni" },
  { id: 21, name: "Khagrachari" },
  { id: 22, name: "Lakshmipur" },
  { id: 23, name: "Noakhali" },
  { id: 24, name: "Rangamati" },
  { id: 25, name: "Barishal" },
  { id: 26, name: "Barguna" },
  { id: 27, name: "Bhola" },
  { id: 28, name: "Jhalokati" },
  { id: 29, name: "Patuakhali" },
  { id: 30, name: "Pirojpur" },
  { id: 31, name: "Khulna" },
  { id: 32, name: "Bagerhat" },
  { id: 33, name: "Chuadanga" },
  { id: 34, name: "Jashore" },
  { id: 35, name: "Jhenaidah" },
  { id: 36, name: "Kushtia" },
  { id: 37, name: "Magura" },
  { id: 38, name: "Meherpur" },
  { id: 39, name: "Narail" },
  { id: 40, name: "Satkhira" },
  { id: 41, name: "Mymensingh" },
  { id: 42, name: "Jamalpur" },
  { id: 43, name: "Netrokona" },
  { id: 44, name: "Sherpur" },
  { id: 45, name: "Rajshahi" },
  { id: 46, name: "Bogura" },
  { id: 47, name: "Joypurhat" },
  { id: 48, name: "Naogaon" },
  { id: 49, name: "Natore" },
  { id: 50, name: "Pabna" },
  { id: 51, name: "Sirajganj" },
  { id: 52, name: "Chapainawabganj" },
  { id: 53, name: "Rangpur" },
  { id: 54, name: "Dinajpur" },
  { id: 55, name: "Gaibandha" },
  { id: 56, name: "Kurigram" },
  { id: 57, name: "Lalmonirhat" },
  { id: 58, name: "Nilphamari" },
  { id: 59, name: "Panchagarh" },
  { id: 60, name: "Thakurgaon" },
  { id: 61, name: "Sylhet" },
  { id: 62, name: "Habiganj" },
  { id: 63, name: "Moulvibazar" },
  { id: 64, name: "Sunamganj" },
];

export const bdDivision = [
  { id: "Dh", name: "Dhaka" },
  { id: "Ch", name: "Chattogram" },
  { id: "Ra", name: "Rajshahi" },
  { id: "Kh", name: "Khulna" },
  { id: "Ba", name: "Barishal" },
  { id: "Sy", name: "Sylhet" },
  { id: "Ran", name: "Rangpur" },
  { id: "My", name: "Mymensingh" },
];

export const dhakaThana = [
  { id: 1, name: "Adabar" },
  { id: '1_1', name: "Agargoan" },
  { id: 2, name: "Badda" },
  { id: 3, name: "Bangshal" },
  { id: 4, name: "Bhashantek" },
  { id: 5, name: "Cantonment" },
  { id: 6, name: "Chawkbazar" },
  { id: 7, name: "Darus Salam" },
  { id: 8, name: "Demra" },
  { id: 9, name: "Dhanmondi" },
  { id: 10, name: "Gandaria" },
  { id: 11, name: "Gulshan" },
  { id: 12, name: "Hazaribagh" },
  { id: 13, name: "Jatrabari" },
  { id: 14, name: "Kafrul" },
  { id: 15, name: "Kalabagan" },
  { id: 16, name: "Kamrangirchar" },
  { id: 17, name: "Khilgaon" },
  { id: 18, name: "Khilkhet" },
  { id: 19, name: "Kadamtali" },
  { id: 20, name: "Kotwali" },
  { id: 21, name: "Lalbagh" },
  { id: 22, name: "Mirpur" },
  { id: 23, name: "Mohammadpur" },
  { id: 24, name: "Motijheel" },
  { id: 25, name: "Mugda" },
  { id: 26, name: "New Market" },
  { id: 27, name: "Pallabi" },
  { id: 28, name: "Paltan" },
  { id: 29, name: "Ramna" },
  { id: 30, name: "Rampura" },
  { id: 31, name: "Rupnagar" },
  { id: 32, name: "Sabujbagh" },
  { id: 33, name: "Shah Ali" },
  { id: 34, name: "Shahbagh" },
  { id: 35, name: "Shahjahanpur" },
  { id: 36, name: "Sher-e-Bangla Nagar" },
  { id: 37, name: "Shyampur" },
  { id: 38, name: "Sutrapur" },
  { id: 39, name: "Tejgaon" },
  { id: 40, name: "Tejgaon Industrial Area" },
  { id: 41, name: "Turag" },
  { id: 42, name: "Uttara East" },
  { id: 43, name: "Uttara West" },
  { id: 44, name: "Uttarkhan" },
  { id: 45, name: "Dakshinkhan" },
  { id: 46, name: "Vatara" },
  { id: 47, name: "Bashundhara" },
  { id: 48, name: "Banasree" },
  { id: 49, name: "Basila" },
  { id: 50, name: "Dhaka Cantonment" },
  { id: 51, name: "Dhamrai" },
  { id: 52, name: "Dohar" },
  { id: 53, name: "Keraniganj" },
  { id: 54, name: "Nawabganj" },
  { id: 55, name: "Savar" },
];
